version: '3.8'

services:
  api:
    build: .
    ports:
      - '2001:5000'
    environment:
      MONGO_URI: mongodb://mongo2:27017/saraha
      JWT_SECRET: 'qwdhqwndhqwdhmiqwkdgqwkjdbqwkjdhqwkdjn'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
