name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: '64.23.184.122'
          username: 'root'
          password: 'pa$$w0rdPP'
          script: |
            cd /root/saraha-nodejs  # Change this to your actual project path
            git pull origin main  # Pull latest code
            docker compose down  # Stop and remove old containers
            docker compose up -d --build  # Rebuild and start new containers
